language: go
sudo: true

before_install:
  - sudo apt-get update -y
  - sudo apt install curl -y
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

notifications:
  email:
    recipients:
      - zpeters@gmail.com
    on_failure: always
    on_success: always
